baseURL = "https://blog.v2.vapor.cloud/"
languageCode = "en-us"
title = "Vapor blog"
copyright = "Copyright © 2008–2018, codevapor"

theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"